{block content}
{control grid}
{/block}

{block code}
<li><a href="http://github.com/PavelMaca/Gridito/blob//editable/app/presenters/{$control->getName()}Presenter.php">Presenter</a></li>
<li><a href="http://github.com/PavelMaca/Gridito/blob//editable/app/templates/{$control->getName()}/default.phtml">View template</a></li>
<li><a href="http://github.com/PavelMaca/Gridito/blob//editable/app/models/UsersGriditoEditableDoctrineModel.php">User model</a></li>
{/block}